language: scala
scala:
- 2.12.2
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
script:
- sbt ++$TRAVIS_SCALA_VERSION --warn update test:compile it:compile && sbt ++$TRAVIS_SCALA_VERSION test it:test && sbt ++$TRAVIS_SCALA_VERSION --warn makeMicrosite
