language: scala
scala:
- 2.11.8
- 2.12.1
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
script:
- sbt ++$TRAVIS_SCALA_VERSION --warn update compile test:compile it:compile && sbt ++$TRAVIS_SCALA_VERSION test it:test && sbt ++$TRAVIS_SCALA_VERSION --warn unidoc
